version: '3.4'
services:
  expense-tracker:
    working_dir: /expensetracker

    image: 192.168.1.188:5000/node:10-alpine
    
    environment:
      - DATABASE_SERVER=mongodb
      - DATABASE_PORT=27017
      - DATABASE_NAME=expense
      - API_SERVER_PORT=3000
      - SEED_DATABASE=false
    
    volumes:
      - type: bind
        source: .
        target: /expensetracker
    
    ports:
      - 3000:3000

  mongodb:
    image: mongo:3.6.10-stretch
    environment:
      - MONGO_INITDB_DATABASE=expense